config/routes.rb
Rails.application.routes.draw do

  resources :traductions, only: :index

  resources :problemes

  resources :categories

  get 'questions/vocabulaire', as: 'questions_vocabulaire'
  get 'questions/conjugaison', as: 'questions_conjugaison'
  get 'questions/revision_conjugaison', as: 'questions_revision_conjugaison'
  get 'questions/revision_vocabulaire', as: 'questions_revision_vocabulaire'
  post 'questions/verification'
  get 'questions', to: 'questions#revision', as: 'questions_revision'
  get 'sauve', to: 'sauve#lance', as: 'lance_sauve'
  post 'ecrit', to: 'sauve#ecrit', as: 'sauve_mot_verbe'
  get 'stats', to: 'stats#affiche', as: 'affiche_stats'

  get 'aide', to: 'aide#show', as:'aide'

  resources :parametres, only: [:edit, :update]

  resources :mots

  resources :verbes

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
    namespace :v2 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
  end

  root 'mots#index'

end

app/models/probleme.rb
class Probleme < ActiveRecord::Base
  belongs_to :user
end

app/controllers/problemes_controller.rb
class ProblemesController < ApplicationController
  before_action :set_probleme, only: [:show, :edit, :update, :destroy]
  before_action :set_autorisations

  # GET /problemes
  # GET /problemes.json
  def index
    @problemes = Probleme.all
  end

  # GET /problemes/1
  # GET /problemes/1.json
  def show
  end

  # GET /problemes/new
  def new
    @probleme = Probleme.new
  end

  # GET /problemes/1/edit
  def edit
  end

  # POST /problemes
  # POST /problemes.json
  def create
    @probleme = Probleme.new(probleme_params)

    respond_to do |format|
      if current_user
        @probleme.user_id = current_user.id
      end
      if @probleme.save
        format.html { redirect_to @probleme, notice: 'Le problème a été enregistré.' }
        format.json { render action: 'show', status: :created, location: @probleme }
      else
        format.html { render action: 'new' }
        format.json { render json: @probleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problemes/1
  # PATCH/PUT /problemes/1.json
  def update
    respond_to do |format|
      if @probleme.update(probleme_params)
        format.html { redirect_to @probleme, notice: 'Le problème a été enregistré.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @probleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problemes/1
  # DELETE /problemes/1.json
  def destroy
    @probleme.destroy
    respond_to do |format|
      format.html { redirect_to problemes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probleme
      @probleme = Probleme.find(params[:id])
    end

  def set_autorisations
    if user_signed_in? and current_user.admin
      @admin = true
    else
      @admin = false
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def probleme_params
      params.require(:probleme).permit(:texte, :corrige, :date_correction)
    end
end

app/helpers/problemes_helper.rb
module ProblemesHelper
end

app/views/problemes/_form.html.haml
= form_for @probleme do |f|
  - if @probleme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@probleme.errors.count, "erreur")} : le problème n'a pas été enregistré."
      %ul
        - @probleme.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :texte
    = f.text_area :texte, size: "40x10", autofocus: true
  -if @admin
    .field
      = f.label :corrige
      = f.check_box :corrige
    .field
      = f.label :date_correction
      = f.datetime_select :date_correction
  .actions
    = f.submit 'Enregistrer'

app/views/problemes/edit.html.haml
%h1 Correction d'un problème

= render 'form'

= link_to 'Voir', @probleme
\|
= link_to 'Retour', problemes_path

app/views/problemes/index.html.haml
%h1 Liste des problèmes

%table
  %tr
    %th Texte
    %th Corrigé
    %th Date correction
    %th
    %th
    %th

  - @problemes.each do |probleme|
    %tr
      %td= probleme.texte
      %td= probleme.corrige
      %td= probleme.date_correction
      %td= link_to 'Voir', probleme
      -if @admin or (current_user and current_user.id == probleme.user_id)
        %td= link_to 'Corr', edit_probleme_path(probleme)
      -else
        %td
      -if @admin
        %td= link_to 'Supp', probleme, :method => :delete, :data => { :confirm => 'Supprimer ?' }
      -else
        %td
%br

= link_to 'Nouveau problème', new_probleme_path

app/views/problemes/new.html.haml
%h1 Nouveau problème

= render 'form'

= link_to 'Retour', problemes_path

app/views/problemes/show.html.haml
%p#notice= notice

%p
  %b Texte:
  = @probleme.texte
%p
  %b Corrige:
  = @probleme.corrige
%p
  %b Date correction:
  = @probleme.date_correction

-if @admin or (current_user and current_user.id == @probleme.user_id)
  = link_to 'Corr', edit_probleme_path(@probleme)
  \|
= button_to 'Nouveau', {action: 'new'}, method: :get, autofocus: true
\|
= link_to 'Retour', problemes_path