config/routes.rb
Rails.application.routes.draw do

  resources :traductions, only: :index

  resources :problemes

  resources :categories

  get 'questions/vocabulaire', as: 'questions_vocabulaire'
  get 'questions/conjugaison', as: 'questions_conjugaison'
  get 'questions/revision_conjugaison', as: 'questions_revision_conjugaison'
  get 'questions/revision_vocabulaire', as: 'questions_revision_vocabulaire'
  post 'questions/verification'
  get 'questions', to: 'questions#revision', as: 'questions_revision'
  get 'sauve', to: 'sauve#lance', as: 'lance_sauve'
  post 'ecrit', to: 'sauve#ecrit', as: 'sauve_mot_verbe'
  get 'stats', to: 'stats#affiche', as: 'affiche_stats'

  get 'aide', to: 'aide#show', as:'aide'

  resources :parametres, only: [:edit, :update]

  resources :mots

  resources :verbes

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
    namespace :v2 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
  end

  root 'mots#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :mots, dependent: :destroy
  has_many :scores_mots, dependent: :restrict_with_error

  def self.sauve
    liste = File.new('db/mots/liste_categories.txt',mode='w')
    IO.write(liste,"liste = [\n")
    Category.all.order(:numero).each do |c|
      IO.write(liste,\
        "["+c.numero.to_s+",\""+c.description+"\"],\n",liste.size)
    end
    IO.write(liste,"]\n",liste.size-2)
    true
  end

  def numero_description
    self.numero.to_s+' '+self.description
  end

  def self.api_v1
    liste = []
    Category.order(:numero).each do |cat|
      liste << [cat.numero, cat.description]
    end
    liste
  end

  def self.api_v2
    liste = []
    Category.order(:numero).each do |cat|
      liste << [cat.id, cat.numero, cat.description]
    end
    liste
  end

end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApplicationController
      def index
        render json: Category.api_v1
      end
    end
  end
end

app/controllers/api/v2/categories_controller.rb
module Api
  module V2
    class CategoriesController < ApplicationController
      def index
        render json: Category.api_v2
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :prepare_user
  before_action :set_autorisations
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:numero)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    if @peut_supprimer
      @category = Category.new
    else
      redirect_to categories_path, notice: "Vous ne pouvez pas créer une nouvelle catégorie"
    end
  end

  # GET /categories/1/edit
  def edit
    unless @peut_supprimer
      redirect_to categories_path, notice: "Vous ne pouvez pas modifier une catégorie"
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'La catégorie a été créée.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'La catégorie a été mise à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if @peut_supprimer
      if @category.destroy
        respond_to do |format|
          format.html { redirect_to categories_url, notice: 'La catégorie a été supprimée.'  }
          format.json { head :no_content }
        end
      else
        redirect_to categories_path, notice: "Impossible de supprimer cette catégorie"
      end
    else
      redirect_to categories_path, notice: "Vous ne pouvez pas supprimer une catégorie"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_autorisations
      @peut_supprimer = false
      if user_signed_in?
        if current_user.admin
          @peut_supprimer = true
        end
      end
    end

    def prepare_user
      if user_signed_in?
        unless current_user.admin
          current_user.init_mots if current_user.mots.empty?
          current_user.init_formes if current_user.formes.empty?
          current_user.init_parametres unless current_user.parametre
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:numero, :description)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "erreur")} : la catégorie n'a pas pu être mise à jour."
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :numero
    = f.number_field :numero
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Enregistrer'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Voir', @category
\|
= link_to 'Retour', categories_path

app/views/categories/index.html.haml
%h1 Liste des catégories

%table
  %tr
    %th Numero
    %th Description
    %th
    %th
    %th

  - @categories.each do |category|
    %tr
      %td= category.numero
      %td= category.description
      %td= link_to 'Voir', category
      -if @peut_supprimer
        %td= link_to 'Corr', edit_category_path(category)
        %td= link_to 'Supp', category, :method => :delete, :data => { :confirm => 'Suppression définitive ?' }
      -else
        %td
        %td
%br

= link_to 'Nouvelle catégorie', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Retour', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Numero:
  = @category.numero
%p
  %b Description:
  = @category.description
%table#category
  %tr
    %th Français
    %th Italien

  -@category.mots.order('mot_directeur').each do |mot|
    %tr
      %td=mot.francais
      %td=mot.italien

= link_to 'Corr', edit_category_path(@category)
\|
= link_to 'Retour', categories_path