config/routes.rb
Rails.application.routes.draw do

  resources :traductions, only: :index

  resources :problemes

  resources :categories

  get 'questions/vocabulaire', as: 'questions_vocabulaire'
  get 'questions/conjugaison', as: 'questions_conjugaison'
  get 'questions/revision_conjugaison', as: 'questions_revision_conjugaison'
  get 'questions/revision_vocabulaire', as: 'questions_revision_vocabulaire'
  post 'questions/verification'
  get 'questions', to: 'questions#revision', as: 'questions_revision'
  get 'sauve', to: 'sauve#lance', as: 'lance_sauve'
  post 'ecrit', to: 'sauve#ecrit', as: 'sauve_mot_verbe'
  get 'stats', to: 'stats#affiche', as: 'affiche_stats'

  get 'aide', to: 'aide#show', as:'aide'

  resources :parametres, only: [:edit, :update]

  resources :mots

  resources :verbes

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
    namespace :v2 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
  end

  root 'mots#index'

end

app/models/verbe.rb
class Verbe < ActiveRecord::Base

  has_many :formes, -> { order "rang_forme" }, dependent: :destroy
  accepts_nested_attributes_for :formes
  has_many :scores_formes, through: :formes, dependent: :destroy
  accepts_nested_attributes_for :scores_formes
  has_many :erreurs, through: :formes, dependent: :destroy

  validates :infinitif, presence: {message: "L'infinitif est obligatoire"}
  validates :infinitif, uniqueness: {message: 'Le verbe existe déjà' }

  def init(current_user_id)
    Forme::FORMES.each_index do |rang|
    self.formes.build(rang_forme: rang).scores_formes.\
      build(user_id: current_user_id,compteur: Forme::FORMES[rang][3])
    end
    self
  end

  def reduit(user_id)
    self.formes.each do |f|
      if f.italien == ''
        f.scores_formes.each do |sf|
          if sf.user_id == user_id
            sf.compteur = 0
          end
        end
      end
    end
    self
  end

  def ajuste_compteur(fo,user_id,compteur)
    @scores_forme = fo.scores_formes.find_by(user_id: user_id)
    @scores_forme.compteur = compteur
    @scores_forme.rang_forme = fo.rang_forme
    @scores_forme.save!
  end

  def mise_a_jour(vp,user_id)
    @admin = User.find_by(id: user_id).admin
    self.infinitif = vp['infinitif'] if vp['infinitif']
    vp['formes_attributes'].each do |fa|
      fo = self.formes.find_by(rang_forme: fa[1]['rang_forme'].to_i)
      if fa[1]['italien'] == ''
        unless fo.italien == ''
          fo.scores_formes.destroy(fo.scores_formes.where("user_id <> ?",user_id))
        end
        ajuste_compteur(fo,user_id,0)
      else
        if fo.italien == '' and @admin
          User.all.each do |u|
            unless u.id == user_id
              fo.scores_formes.create(user_id: u.id)
            end
            ajuste_compteur(fo,u.id,fa[1]['scores_formes_attributes'].first[1]['compteur'].to_i)
          end
        elsif fa[1]['scores_formes_attributes']
          ajuste_compteur(fo,user_id,fa[1]['scores_formes_attributes'].first[1]['compteur'].to_i)
        end
      end
      fo.italien = fa[1]['italien'] if fa[1]['italien']
      fo.save!
    end
    self.save!
  end

  def self.sauve
    liste = File.new('db/verbes/liste_verbes.txt',mode='w')
    IO.write(liste,"liste = [\n",liste.size)
    Verbe.all.order(:infinitif).each do |v|
      texte = "[\""+v.infinitif+"\",\n["
      v.formes.each do |f|
        texte += "["+f.rang_forme.to_s + ", \"" + f.italien + "\"," + \
          f.scores_formes.find_by(user_id: User.find_by(admin: true).id).compteur.to_s+"],\n"
      end
      IO.write(liste,texte,liste.size)
      IO.write(liste,"]],\n",liste.size-2)
    end
    IO.write(liste,"]\n",liste.size-2)
    true
  end

  def self.api_v1
    liste = []
    Verbe.order(:id).each do |verbe|
      liste << [verbe.id, verbe.infinitif]
    end
    liste
  end

end

app/controllers/api/v1/verbes_controller.rb
module Api
  module V1
    class VerbesController < ApplicationController
      def index
        render json: Verbe.api_v1
      end
    end
  end
end

app/controllers/api/v2/verbes_controller.rb
module Api
  module V2
    class VerbesController < ApplicationController
      def index
        render json: Verbe.api_v1
      end
    end
  end
end

app/controllers/verbes_controller.rb
class VerbesController < ApplicationController

  before_action :prepare_user
  before_action :set_autorisations
  before_action :set_verbe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /verbes
  # GET /verbes.json
  def index
    session[:page_v] = (params[:page] ||= session[:page_v])

    if @peut_corriger and !@peut_supprimer
      @verbes = Verbe.joins(formes: :scores_formes).merge(current_user.liste_scores_formes_a_reviser).\
        select("verbes.id, infinitif, verbes.created_at, verbes.updated_at, sum(compteur) as total_compteur").\
        group("verbes.id","infinitif","verbes.created_at","verbes.updated_at").\
        order(:infinitif).page params[:page]
    else
      @verbes = Verbe.joins(formes: :scores_formes).where("user_id = ?",@user_eq_id).\
        select("verbes.id, infinitif, verbes.created_at, verbes.updated_at, sum(compteur) as total_compteur").\
        group("verbes.id","infinitif","verbes.created_at","verbes.updated_at").\
        order(:infinitif).page params[:page]
    end

  end

  # GET /verbes/1
  # GET /verbes/1.json
  def show
  end

  # GET /verbes/new
  def new
    if @peut_supprimer
      @verbe = Verbe.new.init(current_user.id)
    else
      redirect_to verbes_path, notice: 'Vous ne pouvez pas créer un nouveau verbe'
    end
  end

  # GET /verbes/1/edit
  def edit
  end

  # POST /verbes
  # POST /verbes.json
  def create
    @verbe = Verbe.new(verbe_params).reduit(current_user.id)

    respond_to do |format|
      if @verbe.save
        User.all.each do |u|
          unless u.id == current_user.id
            @verbe.formes.each do |forme|
              unless forme.italien == ''
                forme.scores_formes.each do |score_forme_admin|
                  u.scores_formes.create(forme_id: score_forme_admin.forme_id,\
                    compteur: score_forme_admin.compteur, rang_forme: forme.rang_forme)
                end
              end
            end
          end
        end
        format.html { redirect_to @verbe, notice: 'Le verbe a bien été créé.' }
        format.json { render action: 'show', status: :created, location: @verbe }
      else
        format.html { render action: 'new' }
        format.json { render json: @verbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verbes/1
  # PATCH/PUT /verbes/1.json
  def update
    respond_to do |format|
      if @verbe.mise_a_jour(verbe_params,current_user.id)
        session[:tableau_formes_ok] = false unless current_user.admin
        format.html { redirect_to @verbe, notice: 'Le verbe a été mis à jour.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @verbe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verbes/1
  # DELETE /verbes/1.json
  def destroy
    if @peut_supprimer
      @verbe.destroy
      respond_to do |format|
        format.html { redirect_to verbes_url, notice: 'Le verbe a été supprimé.' }
        format.json { head :no_content }
      end
    else
      redirect_to verbes_path, notice: "Vous ne pouvez pas supprimer un verbe"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verbe
      @verbe = Verbe.find(params[:id])
    end

    def set_autorisations
      @peut_corriger = false
      @peut_supprimer = false
      if user_signed_in?
        if current_user.admin
          @peut_corriger = true
          @peut_supprimer = true
        else
          @peut_corriger = true
        end
      end
      if @peut_corriger and not @peut_supprimer
        @user_eq_id = current_user.id
      else
        @user_eq_id = User.where(admin: true).first.id
      end
    end

  def prepare_user
    if user_signed_in?
      unless current_user.admin
        current_user.init_mots if current_user.scores_mots.empty?
        current_user.init_formes if current_user.scores_formes.empty?
        current_user.init_parametres unless current_user.parametre
      end
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verbe_params
      params.require(:verbe).permit(:infinitif, formes_attributes: [:rang_forme, :italien, scores_formes_attributes: [:user_id, :compteur]])
    end
end

app/helpers/verbes_helper.rb
module VerbesHelper
end

app/views/verbes/_form.html.haml
= form_for @verbe do |f|
  - if @verbe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@verbe.errors.count, "erreur")} : le verbe n'a pas pu être sauvegardé."
      %ul
        - @verbe.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :infinitif
    = f.text_field :infinitif,:disabled => !(@peut_supprimer)

    -i = 0

    %table#saisie_verbe
      %tr
        %th#t
        %th#p 1ère p. sing.
        %th#c
        %th#p 2ème p. sing.
        %th#c
        %th#p 3ème p. sing.
        %th#c
        %th#p 1ère p. plur.
        %th#c
        %th#p 2ème p. plur.
        %th#c
        %th#p 3ème p. plur.
        %th#c
      %tr
      = f.fields_for :formes do |formes_form|
        -if i/6*6 == i or i == 49
          %tr{class: "#{cycle('pair','impair')}"}
          -texte=Forme::FORMES[i][0]
          %td= formes_form.label :italien, if texte.end_with?('.s1') then texte[0..-4] else texte end
        -if @peut_supprimer or formes_form.object.italien != ''
          %td= formes_form.text_field :italien, size: 20, class: 'italien', :disabled => !(@peut_supprimer)
        -else
          %td.italien
        =formes_form.hidden_field :rang_forme
        -aucune_ligne = true
        = formes_form.fields_for :scores_formes do |scores_formes|
          -if scores_formes.object.user_id == current_user.id
            -aucune_ligne = false
            %td= scores_formes.number_field :compteur, class: 'compteur'
            =scores_formes.hidden_field :user_id
        -if aucune_ligne
          %td.compteur
        -i+=1


  %br

  .actions
    = f.submit 'Enregistrer'

app/views/verbes/edit.html.haml
%h1 Correction d'un verbe

= render 'form'

= link_to 'Voir', @verbe
\|
= link_to 'Retour', verbes_path

app/views/verbes/index.html.haml
%h1 Liste des verbes
%p#notice= notice

%table#verbe
  %tr
    %th Infinitif
    %th Compteur
    %th Créé le
    %th Modifié le
    %th
    -if @peut_corriger
      %th
    -if @peut_supprimer
      %th

  - @verbes.each do |verbe|
    %tr
      %td= verbe.infinitif
      %td= verbe.total_compteur
      %td= verbe.created_at.strftime('%Y/%m/%d')
      %td= verbe.updated_at.strftime('%Y/%m/%d')
      %td= link_to 'Voir', verbe
      -if @peut_corriger
        %td= link_to 'Corr', edit_verbe_path(verbe)
      -if @peut_supprimer
        %td= link_to 'Supp', verbe, :method => :delete, :data => { :confirm => 'Supprimer ?' }

%br
= paginate @verbes
-if @peut_supprimer
  = link_to 'Nouveau', new_verbe_path

app/views/verbes/new.html.haml
%h1 Nouveau verbe

= render 'form'

= link_to 'Retour', verbes_path

app/views/verbes/show.html.haml
%p#notice= notice

%p
  %b Infinitif:
  = @verbe.infinitif
%p

%table#verbe1
  %tr
    %th#mode
    %th PRESENT
    %th IMPARFAIT
    %th PARFAIT
    %th FUTUR
  %tr
    %td#gras{:rowspan => 11} INDICATIF
    -(0..5).each do |personne|
      -(0..3).each do |temps|
        -rang = temps * 6 + personne
        -forme = @verbe.formes.find_by(rang_forme: rang)
        -if forme and forme.italien != ''
          %td=Forme::FORMES[rang][1]+' '+forme.italien+' ('+forme.scores_formes.find_by(user_id: @user_eq_id).compteur.to_s+')'
        -else
          %td -
      %tr

%table#verbe2
  %tr
    %th#mode
    %th PRESENT
    %th IMPARFAIT
    %th IMPERATIF
    %th CONDITIONNEL
  %tr
    %td#gras{:rowspan => 11} SUBJONCTIF
    -(0..5).each do |personne|
      -(4..7).each do |temps|
        -rang = temps * 6 + personne
        -forme = @verbe.formes.find_by(rang_forme: rang)
        -if forme and forme.italien != ''
          %td=Forme::FORMES[rang][1]+' '+forme.italien+' ('+forme.scores_formes.find_by(user_id: @user_eq_id).compteur.to_s+')'
        -else
          %td -
      %tr
%table#verbe3
  %tr
    %th GERONDIF
    %th PARTICIPE PASSE

  %tr
    -(48..49).each do |rang|
      -forme = @verbe.formes.find_by(rang_forme: rang)
      -if forme and forme.italien != ''
        %td=Forme::FORMES[rang][1]+' '+forme.italien+' ('+forme.scores_formes.find_by(user_id: @user_eq_id).compteur.to_s+')'
      -else
        %td -
= link_to 'Corriger', edit_verbe_path(@verbe)
\|
= link_to 'Retour', verbes_path