config/routes.rb
Rails.application.routes.draw do

  resources :traductions, only: :index

  resources :problemes

  resources :categories

  get 'questions/vocabulaire', as: 'questions_vocabulaire'
  get 'questions/conjugaison', as: 'questions_conjugaison'
  get 'questions/revision_conjugaison', as: 'questions_revision_conjugaison'
  get 'questions/revision_vocabulaire', as: 'questions_revision_vocabulaire'
  post 'questions/verification'
  get 'questions', to: 'questions#revision', as: 'questions_revision'
  get 'sauve', to: 'sauve#lance', as: 'lance_sauve'
  post 'ecrit', to: 'sauve#ecrit', as: 'sauve_mot_verbe'
  get 'stats', to: 'stats#affiche', as: 'affiche_stats'

  get 'aide', to: 'aide#show', as:'aide'

  resources :parametres, only: [:edit, :update]

  resources :mots

  resources :verbes

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
    namespace :v2 do
      resources :date_categories, :categories,
                :date_mots, :mots,
                :date_verbes, :verbes,
                :date_formes, :formes, only: [:index]
    end
  end

  root 'mots#index'

end

app/views/layouts/_droite.html.haml
%h3 Activité du jour
-if current_user and not current_user.admin
  -res=current_user.sessions.where("date(debut) = ?", Date.today).select("sum(fin-debut) as duree, sum(bonnes_reponses) as bonnes,sum(mauvaises_reponses) as mauvaises").take
  -if res.duree and (res.bonnes + res.mauvaises) > 0
    %h4="Révision pendant #{res.duree}"
    %h4="#{res.bonnes+res.mauvaises} #{'question'.pluralize(res.bonnes+res.mauvaises)}"
    %h4="#{res.bonnes*100/(res.bonnes+res.mauvaises)} % de réussite"
  -else
    %h4 Pas de révision aujourd'hui !

app/views/layouts/_gauche.html.haml
-if current_user
  %h3=current_user.email
  -if current_user.admin
    Administrateur
  -else
    -par=Parametre.find_by(user_id: current_user.id)
    %h3 Paramètres pour les mots
    %h4="#{Category.find(par.voc_category).description}" unless par.voc_category.blank?
    %h4="Compteur >= #{par.voc_compteur_min}" unless par.voc_compteur_min.blank?
    %h4="1ère révision >= #{par.voc_revision_1_min}" unless par.voc_revision_1_min.blank?
    %h4="Non révisés depuis #{par.voc_delai_revision} #{'jour'.pluralize(par.voc_delai_revision)}" unless par.voc_delai_revision.blank?
    %h4="#{par.tableau_ids_mots.size} points" unless par.tableau_ids_mots.blank? or not session[:tableau_mots_ok]
    %h3 Paramètres pour les formes verbales
    %h4="#{Forme::TEMPS.flatten[Forme::TEMPS.flatten.find_index(par.for_temps.to_range) - 1]}" unless par.for_temps.blank?
    %h4="Compteur >= #{par.for_compteur_min}" unless par.for_compteur_min.blank?
    %h4="1ère révision >= #{par.for_revision_1_min}" unless par.for_revision_1_min.blank?
    %h4="Non révisés depuis #{par.for_delai_revision} #{'jour'.pluralize(par.for_delai_revision)}" unless par.for_delai_revision.blank?
    %h4="#{par.tableau_ids_formes.size} points" unless par.tableau_ids_formes.blank? or not session[:tableau_mots_ok]

-else
  %h3 Non identifié

app/views/layouts/_header.html.haml
%header#page_header
  %table
    %th=link_to 'Catégories', categories_path \
    %th=link_to 'Vocabulaire', mots_path \
    %th=link_to 'Conjugaisons', verbes_path \
    -if user_signed_in? and not current_user.admin
      %th=link_to 'Révision vocabulaire', questions_revision_vocabulaire_path, :data => {:vocabulaire => true} \
      %th=link_to 'Révision conjugaisons', questions_revision_conjugaison_path, :data => {:conjugaison => true} \
      %th=link_to 'Révision', questions_revision_path \
      %th=link_to 'Paramétrage', edit_parametre_path(current_user.parametre) \
    -if user_signed_in? and current_user.admin
      %th=link_to 'Sauve', lance_sauve_path
    -if user_signed_in?
      %th=link_to 'Déconnexion', destroy_user_session_path, method: :delete
    -else
      %th=link_to 'Connexion', new_user_session_path
    %th=link_to '?', aide_path
    %th=link_to 'Erreur',new_probleme_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Italien</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <section id="sidebar-left">
      <%= render 'layouts/gauche' %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar-right">
      <%= render 'layouts/droite' %>
    </section>
  </div>
</body>
</html>